FROM openjdk:17
VOLUME /tmp
EXPOSE 8080
ARG JAR_FILE=target/SocialMediaInteraction-1.0.0.jar
ADD ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
ENV JAVA_OPTS="-Xss512k -XX:+UseG1GC -XX:GCTimeRatio=4 -XX:MaxGCPauseMillis=200"

#Copy your shell script intop image
copy start.sh /start.sh

#Make the script excecutable
RUN chmod +x /start.sh

CMD ["/start.sh"
#!/bin/sh
exec java $JAVA_OPTS -jar /app.jar